"""empty message

Revision ID: 18deab09869a
Revises: 5882932bae87
Create Date: 2015-03-26 14:02:27.259981

"""

# revision identifiers, used by Alembic.
revision = '18deab09869a'
down_revision = '5882932bae87'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
