"""empty message

Revision ID: 230809aa3f2d
Revises: b8cdad60b6a
Create Date: 2015-03-26 15:20:14.251428

"""

# revision identifiers, used by Alembic.
revision = '230809aa3f2d'
down_revision = 'b8cdad60b6a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_literature', 'id')
    op.drop_column('data_set_literature', 'id')
    op.execute("ALTER TABLE data_set_literature ADD CONSTRAINT pk_data_set_literature PRIMARY KEY (data_set_id, literature_id);")
    op.execute("ALTER TABLE code_literature ADD CONSTRAINT pk_code_literature PRIMARY KEY (code_id, literature_id);")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data_set_literature', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    op.add_column('code_literature', sa.Column('id', mysql.INTEGER(display_width=11), nullable=False))
    ### end Alembic commands ###
