"""empty message

Revision ID: 230f3e3f7ef0
Revises: 13899806ae36
Create Date: 2015-03-20 23:17:11.690910

"""

# revision identifiers, used by Alembic.
revision = '230f3e3f7ef0'
down_revision = '13899806ae36'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_set_literature',
    sa.Column('data_set_id', sa.Integer(), nullable=True),
    sa.Column('literature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['data_set_id'], ['data_set.id'], ),
    sa.ForeignKeyConstraint(['literature_id'], ['literature_meta.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data_set_literature')
    ### end Alembic commands ###
