"""empty message

Revision ID: 2a1716dd9363
Revises: 4b6abe16f9f0
Create Date: 2015-03-24 14:56:58.047511

"""

# revision identifiers, used by Alembic.
revision = '2a1716dd9363'
down_revision = '4b6abe16f9f0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_attribute')
    op.drop_column('attribute', 'type')
    op.create_foreign_key(None, 'cite', 'type', ['cite_type_id'], ['id'])
    op.alter_column('code', 'uri',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=256),
               nullable=False)
    op.create_foreign_key(None, 'favorite', 'user', ['user_id'], ['id'])
    op.add_column('literature_meta', sa.Column('DOI', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('ISBN', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('ISSN', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('abstractCN', sa.Text(), nullable=True))
    op.add_column('literature_meta', sa.Column('authorCN', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('edition', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('editor', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('institute', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('instructor', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('issue', sa.Integer(), nullable=True))
    op.add_column('literature_meta', sa.Column('key_words_CN', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('language', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('location', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('press', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('publisher', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('publisherCN', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('section', sa.Integer(), nullable=True))
    op.add_column('literature_meta', sa.Column('titleCN', sa.String(length=256), nullable=True))
    op.add_column('literature_meta', sa.Column('volume', sa.Integer(), nullable=True))
    op.drop_column('literature_meta', 'link')
    op.drop_constraint(u'ppt_ibfk_3', 'ppt', type_='foreignkey')
    op.drop_constraint(u'ppt_ibfk_1', 'ppt', type_='foreignkey')
    op.drop_column('ppt', 'update_time')
    op.drop_column('ppt', 'description')
    op.drop_column('ppt', 'title')
    op.drop_column('ppt', 'creator_id')
    op.drop_column('ppt', 'create_time')
    op.drop_column('ppt', 'pages')
    op.drop_column('ppt', 'updater_id')
    op.drop_constraint(u'video_ibfk_3', 'video', type_='foreignkey')
    op.drop_constraint(u'video_ibfk_1', 'video', type_='foreignkey')
    op.drop_column('video', 'update_time')
    op.drop_column('video', 'description')
    op.drop_column('video', 'title')
    op.drop_column('video', 'creator_id')
    op.drop_column('video', 'create_time')
    op.drop_column('video', 'updater_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video', sa.Column('updater_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('video', sa.Column('create_time', mysql.DATETIME(), nullable=False))
    op.add_column('video', sa.Column('creator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('video', sa.Column('title', mysql.VARCHAR(collation=u'utf8_bin', length=256), nullable=False))
    op.add_column('video', sa.Column('description', mysql.TEXT(collation=u'utf8_bin'), nullable=True))
    op.add_column('video', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.create_foreign_key(u'video_ibfk_1', 'video', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(u'video_ibfk_3', 'video', 'user', ['updater_id'], ['id'])
    op.add_column('ppt', sa.Column('updater_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ppt', sa.Column('pages', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('ppt', sa.Column('create_time', mysql.DATETIME(), nullable=False))
    op.add_column('ppt', sa.Column('creator_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.add_column('ppt', sa.Column('title', mysql.VARCHAR(collation=u'utf8_bin', length=256), nullable=False))
    op.add_column('ppt', sa.Column('description', mysql.TEXT(collation=u'utf8_bin'), nullable=True))
    op.add_column('ppt', sa.Column('update_time', mysql.DATETIME(), nullable=True))
    op.create_foreign_key(u'ppt_ibfk_1', 'ppt', 'user', ['creator_id'], ['id'])
    op.create_foreign_key(u'ppt_ibfk_3', 'ppt', 'user', ['updater_id'], ['id'])
    op.add_column('literature_meta', sa.Column('link', mysql.VARCHAR(collation=u'utf8_bin', length=256), nullable=True))
    op.drop_column('literature_meta', 'volume')
    op.drop_column('literature_meta', 'titleCN')
    op.drop_column('literature_meta', 'section')
    op.drop_column('literature_meta', 'publisherCN')
    op.drop_column('literature_meta', 'publisher')
    op.drop_column('literature_meta', 'press')
    op.drop_column('literature_meta', 'location')
    op.drop_column('literature_meta', 'language')
    op.drop_column('literature_meta', 'key_words_CN')
    op.drop_column('literature_meta', 'issue')
    op.drop_column('literature_meta', 'instructor')
    op.drop_column('literature_meta', 'institute')
    op.drop_column('literature_meta', 'editor')
    op.drop_column('literature_meta', 'edition')
    op.drop_column('literature_meta', 'authorCN')
    op.drop_column('literature_meta', 'abstractCN')
    op.drop_column('literature_meta', 'ISSN')
    op.drop_column('literature_meta', 'ISBN')
    op.drop_column('literature_meta', 'DOI')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.alter_column('code', 'uri',
               existing_type=mysql.VARCHAR(collation=u'utf8_bin', length=256),
               nullable=True)
    op.drop_constraint(None, 'cite', type_='foreignkey')
    op.add_column('attribute', sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    op.create_table('comment_attribute',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('comment_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('attribute_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('value', mysql.TEXT(collation=u'utf8_bin'), nullable=True),
    sa.ForeignKeyConstraint(['attribute_id'], [u'attribute.id'], name=u'comment_attribute_ibfk_1'),
    sa.ForeignKeyConstraint(['comment_id'], [u'comment.id'], name=u'comment_attribute_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate=u'utf8_bin',
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
