"""empty message

Revision ID: 3a0598059847
Revises: f2c7d45c63c
Create Date: 2015-03-26 14:45:07.249565

"""

# revision identifiers, used by Alembic.
revision = '3a0598059847'
down_revision = 'f2c7d45c63c'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_literature', 'id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_literature', sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
    ### end Alembic commands ###
