"""empty message

Revision ID: 43f8a1b8805c
Revises: 9c4ce2f65f1
Create Date: 2015-03-20 21:49:50.446928

"""

# revision identifiers, used by Alembic.
revision = '43f8a1b8805c'
down_revision = '9c4ce2f65f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('literature_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=256), nullable=True),
    sa.Column('published_year', sa.Integer(), nullable=True),
    sa.Column('key_words', sa.String(length=256), nullable=True),
    sa.Column('link', sa.String(length=256), nullable=True),
    sa.Column('pages', sa.Integer(), nullable=True),
    sa.Column('uri', sa.String(length=256), nullable=True),
    sa.Column('creator_id', sa.Integer(), nullable=False),
    sa.Column('updater_id', sa.Integer(), nullable=True),
    sa.Column('literature_type_id', sa.Integer(), nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=False),
    sa.Column('update_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['literature_type_id'], ['type.id'], ),
    sa.ForeignKeyConstraint(['updater_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('literature_meta')
    op.drop_table('type')
    ### end Alembic commands ###
