"""empty message

Revision ID: 4b6abe16f9f0
Revises: 51487a60d7e0
Create Date: 2015-03-21 11:58:40.241794

"""

# revision identifiers, used by Alembic.
revision = '4b6abe16f9f0'
down_revision = '51487a60d7e0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'tag_resource', 'tag', ['tag_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag_resource', type_='foreignkey')
    ### end Alembic commands ###
