"""empty message

Revision ID: 4e1e4fc457fb
Revises: 230f3e3f7ef0
Create Date: 2015-03-20 23:58:29.012671

"""

# revision identifiers, used by Alembic.
revision = '4e1e4fc457fb'
down_revision = '230f3e3f7ef0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_literature',
    sa.Column('code_id', sa.Integer(), nullable=True),
    sa.Column('literature_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['code_id'], ['code.id'], ),
    sa.ForeignKeyConstraint(['literature_id'], ['literature_meta.id'], )
    )
    op.create_table('cite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('literature_id', sa.Integer(), nullable=False),
    sa.Column('cited_id', sa.Integer(), nullable=False),
    sa.Column('cite_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cited_id'], ['literature_meta.id'], ),
    sa.ForeignKeyConstraint(['literature_id'], ['literature_meta.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cite')
    op.drop_table('code_literature')
    ### end Alembic commands ###
