"""empty message

Revision ID: 5882932bae87
Revises: 2a1716dd9363
Create Date: 2015-03-26 13:57:29.477303

"""

# revision identifiers, used by Alembic.
revision = '5882932bae87'
down_revision = '2a1716dd9363'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
