"""empty message

Revision ID: b8cdad60b6a
Revises: 3bc597926ec5
Create Date: 2015-03-26 15:11:24.803420

"""

# revision identifiers, used by Alembic.
revision = 'b8cdad60b6a'
down_revision = '3bc597926ec5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comment', sa.Column('isSimple', sa.Integer(), nullable=False))
    op.execute("ALTER TABLE data_set_literature ADD id INT PRIMARY KEY AUTO_INCREMENT;")
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_set_literature', 'id')
    op.drop_column('comment', 'isSimple')
    ### end Alembic commands ###
