"""empty message

Revision ID: f2c7d45c63c
Revises: 1838685e563a
Create Date: 2015-03-26 14:17:59.832742

"""

# revision identifiers, used by Alembic.
revision = 'f2c7d45c63c'
down_revision = '1838685e563a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
